#!/usr/bin/env bash
set -euo pipefail

export PATH="/usr/bin:/bin:$PATH"

SCRIPT_PATH="${BASH_SOURCE[0]}"
SCRIPT_DIR="$(cd "${SCRIPT_PATH%/*}" && pwd)"
REPO="${FEVIO_REPO:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
cd "$REPO"

DATE="$(TZ=Asia/Seoul date +%F)"
BRANCH="agent/daily-git-history-$DATE"
DIGEST="docs/06-hw/daily-git-history/$DATE.md"
PROMPT="/tmp/hermes-review-$DATE.txt"
ALLOWED_PATH_REGEX='^(docs/06-hw/|scripts/hw6/|docker/hw6-git-history-agent/)'

echo "== Fevio Hermes daily git review: $DATE =="

echo "== Checking local prerequisites =="
for command_name in git docker hermes gh; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "ERROR: Required command is not available on PATH: $command_name"
    exit 1
  fi
done

if [ -n "$(git status --porcelain --untracked-files=all)" ]; then
  echo "ERROR: Working tree must be clean before the full daily PR loop runs."
  git status --short
  exit 1
fi

echo "== Fetching origin/main =="
git fetch origin main

echo "== Creating or resetting branch: $BRANCH =="
git switch main
git pull --ff-only origin main
git switch -C "$BRANCH"

echo "== Building Docker image =="
docker build -t fevio-git-history-agent -f docker/hw6-git-history-agent/Dockerfile docker/hw6-git-history-agent

echo "== Running Dockerized git history digest =="
docker run --rm \
  -e DIGEST_DATE="$DATE" \
  -v "$PWD:/workspace:ro" \
  -v "$PWD/docs/06-hw:/workspace/docs/06-hw:rw" \
  -w /workspace \
  fevio-git-history-agent

if [ ! -f "$DIGEST" ]; then
  echo "Digest was not created: $DIGEST"
  exit 1
fi

echo "== Preparing Hermes review prompt =="
sed "s/{{DATE}}/$DATE/g" scripts/hw6/hermes-review-template.txt > "$PROMPT"

echo "== Running Hermes review =="
echo "If this hangs, your Hermes CLI needs a non-interactive command. Check: hermes chat --help"

hermes chat < "$PROMPT"

echo "== Verifying Hermes review quality =="
if ! grep -q '^## Hermes Review$' "$DIGEST"; then
  echo "ERROR: Hermes did not add a '## Hermes Review' section to $DIGEST"
  exit 1
fi

HERMES_REVIEW_LINES="$(awk '
  /^## Hermes Review$/ { in_section = 1; next }
  /^## / && in_section { in_section = 0 }
  in_section && NF { count++ }
  END { print count + 0 }
' "$DIGEST")"

if [ "$HERMES_REVIEW_LINES" -lt 5 ]; then
  echo "ERROR: Hermes Review section is too thin; expected at least 5 non-empty lines."
  exit 1
fi

echo "== Checking changed files =="
git status --short

BAD_FILES="$(git status --porcelain --untracked-files=all | awk -v allowed="$ALLOWED_PATH_REGEX" '
  {
    path = substr($0, 4)
    if ($0 ~ /^R/ || $0 ~ /^C/) {
      split(path, parts, " -> ")
      path = parts[2]
    }
    if (path !~ allowed) {
      print path
    }
  }
')"

if [ -n "$BAD_FILES" ]; then
  echo "ERROR: Hermes or the loop modified files outside the allowed scope:"
  echo "$BAD_FILES"
  echo "Aborting. Please review and revert these files."
  exit 1
fi

echo "== Checking whether there are changes to commit =="
if [ -z "$(git status --porcelain docs/06-hw scripts/hw6 docker/hw6-git-history-agent)" ]; then
  echo "No changes to commit."
  exit 0
fi

echo "== Committing changes =="
git add docs/06-hw scripts/hw6 docker/hw6-git-history-agent
git commit -m "Add daily Hermes git history review for $DATE"

echo "== Pushing branch =="
git push -u origin "$BRANCH" --force-with-lease

echo "== Creating PR =="
if gh pr view "$BRANCH" >/dev/null 2>&1; then
  echo "PR already exists for $BRANCH"
else
  gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "Daily Hermes git history review - $DATE" \
    --body "This PR was generated by the HW9 on-premise Docker + Hermes loop.

Summary:
- Docker generated the daily git history digest.
- Hermes reviewed the digest and added Fevio-specific interpretation.
- Write scope was constrained to docs/06-hw/.
- No app code, src files, Supabase files, secrets, deployment files, issues, or PRs were modified by the agent.
"
fi

echo "== Enabling auto-merge =="
gh pr merge "$BRANCH" --squash --auto

echo "== Done =="
