export const fevioTokens = {
  color: {
    sage: '#6F8F6E',
    sageDark: '#3D5C3C',
    lavender: '#B9AED6',
    cream: '#F6F4F1',
    coral: '#E07A68',
    sky: '#F0F9FF',
    softGray: '#F3F4F6',
    border: '#E5E7EB',
    secondaryText: '#6B7280',
    tertiaryText: '#9CA3AF',
    ink: '#20231F',
    muted: '#686F64',
    card: '#FFFFFF',
    slcBg: '#FAF7F2',
    slcSurface: '#FFFDFC',
    slcCoral: '#D95F4C',
    slcCoralLight: '#FFF1EB',
    slcCoralDark: '#B94F3D',
    slcCoralGradient: 'linear-gradient(135deg, #F47D63 0%, #D95F4C 100%)',
    slcBorder: '#E9DED6',
    slcText: '#2F2926',
    slcMuted: '#8A7F78',
    slcSuccess: '#6E8F72',
    slcCard: '#FFFFFF',
  },
  semantic: {
    background: 'var(--fevio-cream)',
    surface: 'var(--fevio-card)',
    infoSurface: 'var(--fevio-sky)',
    patientAccent: 'var(--fevio-sage)',
    partnerAccent: 'var(--fevio-lavender)',
    reminderAccent: 'var(--fevio-coral)',
    clinicalNeutral: 'var(--fevio-soft-gray)',
    textPrimary: 'var(--fevio-ink)',
    textSecondary: 'var(--fevio-text-secondary)',
    textTertiary: 'var(--fevio-text-tertiary)',
    slcBackground: 'var(--slc-bg)',
    slcSurface: 'var(--slc-surface)',
    slcAccent: 'var(--slc-coral)',
    slcActive: 'var(--slc-coral-light)',
    slcPrimaryCta: 'var(--slc-coral-gradient)',
    slcBorder: 'var(--slc-border)',
    slcText: 'var(--slc-text)',
    slcMuted: 'var(--slc-muted)',
    slcSuccess: 'var(--slc-success)',
  },
  material: {
    ultraThinBlur: '20px',
    thinBlur: '30px',
    regularBlur: '40px',
    thickBlur: '50px',
    ultraThickBlur: '60px',
    glassEdge: 'rgba(255, 255, 255, 0.42)',
    softShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    cardShadow: '0 20px 60px rgba(50, 61, 46, 0.12)',
    grainTexture: 'var(--fevio-grain-texture)',
  },
  typography: {
    koreanFamily: 'var(--font-noto-sans-kr), -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", system-ui, sans-serif',
    bodyMin: '16px',
    sectionLabelSize: '11px',
    bodyHelpSize: '12px',
    questionTitleSize: '24px',
    questionTitleLineHeight: '130%',
  },
  radius: {
    card: '22px',
    cardTight: '16px',
    control: '999px',
    badge: '999px',
    phone: '53px',
  },
  touchTarget: {
    minHeight: '48px',
  },
  device: {
    iphone17ProMax: {
      width: '440px',
      height: '956px',
      safeTop: '59px',
      safeBottom: '34px',
      bezelWidth: '5px',
      demoBezelWidth: '3px',
      screenInset: '7px',
      dynamicIslandTop: '11px',
      dynamicIslandWidth: '125.67px',
      dynamicIslandHeight: '36.67px',
      dynamicIslandRadius: '18.33px',
    },
  },
  careOS: {
    phases: {
      cos: {
        label: '과배란 유도',
        patientState: '주사 공포와 신체 피로',
        partnerRole: '준비 지원자',
      },
      trigger: {
        label: '최종 성숙',
        patientState: '골든타임 불안',
        partnerRole: '타이머 감시자',
      },
      opu: {
        label: '난자 채취',
        patientState: '급성 스트레스와 회복 필요',
        partnerRole: '이동 동행자',
      },
      culture: {
        label: '배아 배양',
        patientState: '성적표를 기다리는 마음',
        partnerRole: '정보 공동 수신자',
      },
      tww: {
        label: '이식 후 대기',
        patientState: '과각성과 희망/절망 반복',
        partnerRole: '정서적 지지자',
      },
    },
  },
} as const;

export type FevioTone = 'sage' | 'lavender' | 'coral' | 'neutral';
